#+title: Config

* Information
My personal information.
#+begin_src emacs-lisp
(setq user-full-name "wusitee"
      user-mail-address "kekdkkwk@outlook.com")
#+end_src
* Client
** Workspace
Prevent client from creating new workspace.
#+begin_src emacs-lisp
(after! persp-mode
  (setq persp-emacsclient-init-frame-behaviour-override "main"))
#+end_src
** font
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Maple Mono SC NF" :size 16 ))
#+end_src
** Transparency
Make client transparent.
#+begin_src emacs-lisp
(set-frame-parameter nil 'alpha-background 90)
(add-to-list 'default-frame-alist '(alpha-background . 90))
#+end_src
** Line number
#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src
** Theme
#+begin_src emacs-lisp
(setq doom-theme 'doom-one)
#+end_src
* Terminal
Using fish for v-term.
#+begin_src emacs-lisp
(setq shell-file-name (executable-find "bash"))
(setq-default vterm-shell (executable-find "fish"))
(setq vterm-timer-delay 0) ;; make vterm smoother
#+end_src
* Tools
** Spelling check
Set the spelling check to en-US
#+begin_src emacs-lisp
(after! langtool
  (setq langtool-default-language "en-US"))
#+end_src
** lsp
Follow the [[https://emacs-lsp.github.io/lsp-mode/page/performance/][Performance page]]:
#+begin_src emacs-lisp
(setq gc-cons-threshold 100000000)
(setq read-process-output-max (* 1024 1024)) ;; 1mb
#+end_src
** Direnv
#+begin_src emacs-lisp
(add-hook 'after-init-hook 'envrc-global-mode)
#+end_src

* Snippets
** snippet dir
Set the snippet dirs.
#+begin_src emacs-lisp
(setq yas-snippet-dirs '("~/.config/doom/snippets/"))
#+end_src
** tab conflict
Resolve the tab conflict.
#+begin_src emacs-lisp
(defun yas/org-very-safe-expand ()
  (let ((yas/fallback-behavior 'return-nil)) (yas/expand)))
(add-hook 'org-mode-hook
          (lambda ()
            (make-variable-buffer-local 'yas/trigger-key)
            (setq yas/trigger-key [tab])
            (add-to-list 'org-tab-first-hook 'yas/org-very-safe-expand)
            (define-key yas/keymap [tab] 'yas-next-field)))
#+end_src
* Completion
** Vertico
Add Chinese pinyin search support to Vertico.
#+begin_src emacs-lisp
(defun pyin-orderless-regexp (orig-func component)
  (let ((result (funcall orig-func component)))
    (pyim-cregexp-build result)))

(advice-add 'orderless-regexp :around #'pyin-orderless-regexp)
#+end_src

** Copilot
Use copilot when needed.
#+begin_src emacs-lisp
(use-package! copilot
  ;; :hook (prog-mode . copilot-mode)
  :bind (:map copilot-completion-map
              ("<tab>" . 'copilot-accept-completion)
              ("TAB" . 'copilot-accept-completion)
              ("C-TAB" . 'copilot-accept-completion-by-word)
              ("C-<tab>" . 'copilot-accept-completion-by-word)))
#+end_src
* lang
** Org
*** Latex preview
#+begin_src emacs-lisp
(use-package! org-latex-preview
  :config
  ;; Increase preview width
  (plist-put org-latex-preview-appearance-options
             :page-width 1.0)

  ;; Use dvisvgm to generate previews
  ;; You don't need this, it's the default:
  (setq org-latex-preview-process-default 'dvisvgm)

  ;; Turn on auto-mode, it's built into Org and much faster/more featured than
  ;; org-fragtog. (Remember to turn off/uninstall org-fragtog.)
  (add-hook 'org-mode-hook 'org-latex-preview-auto-mode)

  ;; Block C-n, C-p etc from opening up previews when using auto-mode
  ;; (setq org-latex-preview-auto-ignored-commands
  ;;       '(next-line previous-line mwheel-scroll
  ;;         scroll-up-command scroll-down-command))

  ;; Enable consistent equation numbering
  (setq org-latex-preview-numbered t)

  ;; Bonus: Turn on live previews.  This shows you a live preview of a LaTeX
  ;; fragment and updates the preview in real-time as you edit it.
  ;; To preview only environments, set it to '(block edit-special) instead
  (setq org-latex-preview-live t)
  ;; Preivew latex when open a file
  (setq org-startup-with-latex-preview t))

  ;; More immediate live-previews -- the default delay is 1 second
  ;; (setq org-latex-preview-live-debounce 0.25))


#+end_src

*** Org Roam UI
#+begin_src emacs-lisp
(use-package! websocket
  :after org-roam)

(use-package! org-roam-ui
  :after org-roam ;; or :after org
  ;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
  ;;         a hookable mode anymore, you're advised to pick something yourself
  ;;         if you don't care about startup time, use
  ;;  :hook (after-init . org-roam-ui-mode)
  :config
  (setq org-roam-ui-sync-theme t
        org-roam-ui-follow t
        org-roam-ui-update-on-save t
        org-roam-ui-open-on-start t))
#+end_src
*** Anki editor
#+begin_src emacs-lisp
(use-package! anki-editor
  :after org
  :hook (org-mode . (lambda ()
                      (if (ignore-errors (anki-editor-api-check))
                          (anki-editor-mode))))
  :config
  (map! :map anki-editor-mode-map
        :leader
        :prefix ("n e" . "Anki Editor")
        :desc "Anki editor mode" "e" #'anki-editor-mode
        :desc "Insert note" "i" #'anki-editor-insert-note
        :desc "Push notes" "p" #'anki-editor-push-notes
        :desc "Cloze note" "c" #'anki-editor-cloze-dwim
        :desc "Delete current note" "d" #'anki-editor-delete-note-at-point
        :desc "Browse current note" "b" #'anki-editor-gui-browse
        :desc "Set current note type" "t" #'anki-editor-set-note-type
        :desc "Push new notes" "P" #'anki-editor-push-new-notes)
  (setq org-export-with-broken-links t))
#+end_src
*** Org Modern
Make org file beautiful.
#+begin_src emacs-lisp
(use-package! org
  :hook
  (org-mode . org-modern-mode)
  (org-agenda-finalize . org-modern-agenda)
  :config
  (setq org-modern-table nil))
#+end_src
*** Latex export
Force page break after toc
#+begin_src emacs-lisp
(setq org-latex-toc-command "\\clearpage \\tableofcontents \\clearpage")
#+end_src
*** org directory
#+begin_src emacs-lisp
(setq org-directory "~/org/")
#+end_src
*** Line number
Disable line number
#+begin_src emacs-lisp
(setq-hook! org-mode display-line-numbers nil)
#+end_src
*** Table Alignment
Use Valign to align table.
| 中文    | 对齐         |
|---------+--------------|
| bush    | 对不齐        |
| 测试    | 好不好        |
| 比较好   | 有点卡        |
| 现在好了 | 这边有点卡     |
| 越大越卡 | 但是不长就不卡 |
| 文言文   | 感觉还可以        |
#+begin_src emacs-lisp
(add-hook! org-mode
           (valign-mode)
           (setq valign-fancy-bar 1))
#+end_src
** Latex
*** Latex viewer
Set default latex viewer to Okular.
#+begin_src emacs-lisp
(setq +latex-viewers '(okular))
#+end_src
